use std::fs;
use std::path::Path;

use tempfile::TempDir;

use pastiche_lint::canonical_sections::CANONICAL_SECTIONS;
use pastiche_lint::report::{format_summary, format_violations};
use pastiche_lint::run_lint;
use pastiche_lint::violation::ViolationFamily;

fn write_file(cwd: &Path, rel: &str, content: &str) {
    let full = cwd.join(rel);
    fs::create_dir_all(full.parent().unwrap()).unwrap();
    fs::write(full, content).unwrap();
}

const VALID_CONFIG: &str = r#"
platform: claude-code
packages:
  - name: "@org/web"
    types: "node_modules/@org/web/dist/index.d.ts"
tokens:
  - "src/styles/tokens.css"
design_md_reference: null
typecheck_command: "tsc --noEmit"
setup_progress:
  action-buttons: stub
  forms-input-collection: stub
  feedback-status: stub
  overlays: stub
  navigation-wayfinding: stub
  content-display: stub
  layout-page-structure: stub
  date-time-selection: stub
  iconography: stub
  visual-hierarchy: stub
  domain-specific-patterns: stub
  brand-identity: stub
  general-wisdom: stub
"#;

const VALID_FACT: &str = "<!-- AUTO-GENERATED by the Pastiche FACT extractor. Do not edit by hand. -->\n\n## Components\n\n```yaml\nButton:\n  pkg: \"@org/web\"\n  variant?: [primary, secondary]\nIconButton:\n  pkg: \"@org/web\"\nForm.Input:\n  pkg: \"@org/form\"\n  name: string\nAvatar: { pkg: \"@org/x\" }\n```\n\n## Tokens\n\n--color-brand-primary\n--color-foreground\n.type-display\n";

fn all_sections_text() -> String {
    CANONICAL_SECTIONS
        .iter()
        .map(|s| format!("## {}\n\n_(empty)_\n", s.name))
        .collect::<Vec<_>>()
        .join("\n")
}

fn write_minimal_project(cwd: &Path, config: Option<&str>, fact: Option<&str>, knowledge: Option<&str>, wisdom: Option<&str>) {
    write_file(cwd, "pastiche/config.yaml", config.unwrap_or(VALID_CONFIG));
    write_file(cwd, "pastiche/FACT.md", fact.unwrap_or(VALID_FACT));
    write_file(cwd, "pastiche/KNOWLEDGE.md", knowledge.unwrap_or(&all_sections_text()));
    write_file(cwd, "pastiche/WISDOM.md", wisdom.unwrap_or(""));
}

#[test]
fn minimal_valid_project_zero_violations() {
    let tmp = TempDir::new().unwrap();
    write_minimal_project(tmp.path(), None, None, None, None);
    let r = run_lint(tmp.path());
    assert!(r.violations.is_empty(), "got: {:?}", r.violations);
    assert!(r.skipped.is_empty());
}

#[test]
fn empty_fact_atoms_sentinel_plus_skips() {
    let tmp = TempDir::new().unwrap();
    let empty_fact = "## Components\n\n```yaml\n```\n\n## Tokens\n";
    write_minimal_project(tmp.path(), None, Some(empty_fact), None, Some("- [Button] should be silenced.\n"));
    let r = run_lint(tmp.path());
    assert!(r.violations.iter().any(|v| v.family == ViolationFamily::Sentinel && v.message.contains("FACT.md has no atoms")));
    assert!(r.skipped.contains(&"wisdom".to_string()));
    assert!(r.skipped.contains(&"knowledge-refs".to_string()));
    assert!(!r.violations.iter().any(|v| v.family == ViolationFamily::Wisdom));
}

#[test]
fn fact_schema_broken_skips_wisdom_knowledge_refs_sections_still_run() {
    let tmp = TempDir::new().unwrap();
    let broken_fact = "## Components\n\n(no fence)\n\n## Tokens\n--foo\n";
    let incomplete_knowledge: String = CANONICAL_SECTIONS[..11]
        .iter()
        .map(|s| format!("## {}\n\n_(empty)_\n", s.name))
        .collect::<Vec<_>>()
        .join("\n");
    write_minimal_project(
        tmp.path(),
        None,
        Some(broken_fact),
        Some(&incomplete_knowledge),
        Some("- [Button] noise that must be suppressed.\n"),
    );
    let r = run_lint(tmp.path());
    assert!(r.violations.iter().any(|v| v.family == ViolationFamily::Fact));
    assert!(r.skipped.contains(&"wisdom".to_string()));
    assert!(r.skipped.contains(&"knowledge-refs".to_string()));
    assert!(r.violations.iter().any(|v| v.family == ViolationFamily::Knowledge && v.message.contains("Brand Identity")));
}

#[test]
fn config_sentinel_plus_fact_failure_both_reported() {
    let tmp = TempDir::new().unwrap();
    let null_platform = VALID_CONFIG.replace("platform: claude-code", "platform: null");
    let broken_fact = "## Components\n\n(no fence)\n\n## Tokens\n";
    write_minimal_project(tmp.path(), Some(&null_platform), Some(broken_fact), None, None);
    let r = run_lint(tmp.path());
    assert!(r.violations.iter().any(|v| v.family == ViolationFamily::Sentinel && v.message.contains("platform not set")));
    assert!(r.violations.iter().any(|v| v.family == ViolationFamily::Fact));
}

#[test]
fn missing_fact_file_sentinel_plus_downstream_skips() {
    let tmp = TempDir::new().unwrap();
    write_file(tmp.path(), "pastiche/config.yaml", VALID_CONFIG);
    write_file(tmp.path(), "pastiche/KNOWLEDGE.md", &CANONICAL_SECTIONS.iter().map(|s| format!("## {}\n", s.name)).collect::<Vec<_>>().join("\n"));
    write_file(tmp.path(), "pastiche/WISDOM.md", "- [Button] noise.\n");
    let r = run_lint(tmp.path());
    assert!(r.violations.iter().any(|v| v.family == ViolationFamily::Sentinel && v.message.contains("FACT.md not found")));
    assert!(r.skipped.contains(&"wisdom".to_string()));
    assert!(r.skipped.contains(&"knowledge-refs".to_string()));
}

#[test]
fn format_clean_report() {
    let tmp = TempDir::new().unwrap();
    write_minimal_project(tmp.path(), None, None, None, None);
    let report = run_lint(tmp.path());
    let summary = format_summary(&report);
    assert!(summary.contains("pastiche:lint \u{2014} cross-doc tag-sanity + schema"));
    assert!(summary.contains("4 components, 3 tokens"));
    assert!(summary.contains("12/12 canonical section(s) present"));
    assert!(summary.contains("pastiche:lint OK \u{2014} 0 violations."));
    let violations = format_violations(&report.violations);
    assert!(violations.is_empty());
}

#[test]
fn format_failing_report() {
    let tmp = TempDir::new().unwrap();
    write_minimal_project(tmp.path(), None, None, None, Some("- [NotAnAtom] bad.\n"));
    let report = run_lint(tmp.path());
    let summary = format_summary(&report);
    assert!(summary.contains("pastiche:lint FAILED"));
    let violations = format_violations(&report.violations);
    assert!(violations.contains("pastiche/WISDOM.md:1") && violations.contains("unknown tag [NotAnAtom]"));
}

#[test]
fn format_skipped_families_annotated() {
    let tmp = TempDir::new().unwrap();
    let empty_fact = "## Components\n\n```yaml\n```\n\n## Tokens\n";
    write_minimal_project(tmp.path(), None, Some(empty_fact), None, Some("- [Button] rule.\n"));
    let report = run_lint(tmp.path());
    let summary = format_summary(&report);
    assert!(summary.contains("WISDOM.md") && summary.contains("SKIPPED"));
    assert!(summary.contains("KNOWLEDGE.md") && summary.contains("SKIPPED"));
}
